### ISSUE TITLE
Tiaoxin algorithm is weak

### ISSUE THREAD

**Issue by CompuRoot** [vstakhov/hpenc#10]
Bellow are multiple sources that stated about weakness of `Tiaoxin` algorithm:

https://competitions.cr.yp.to/round1/tiaoxinv1.pdf

https://www.hindawi.com/journals/scn/2019/1680263/

https://www.researchgate.net/publication/308189562_Differential_Fault_Analysis_on_Tiaoxin_and_AEGIS_Family_of_Ciphers

Suggestion is to remove it or note about it weakness in documentation as well in "help"

**Comment by vstakhov** [comment]
The first paper describes tiaoxin, the second paper describes random fault attack that requires from an attacker to know the plaintext **and** be able to manipulate with ciphertext produced, which I can consider a very unlikely case for `hpenc` applications, the third paper describes some nonce misuse which is, again, not the case for `hpenc`. I can surely remove tiaoxin as I've added it just because I was bored but I would ask for some better clarifications please.

**Comment by CompuRoot** [comment]
My concern was raised from our use case, where partial prefix of original content we encrypting are well know and isn't a secret. As an example, assume it is a shell script and beginning of script filled with long license and all files should contain it, so basically it is repetitive plaintext that available to attacker and might be used in described attack when encrypted files available for attacker. 
I consulted with cryptography engineer regarding this and I believe I raised false alarm, so let's close this issue since there no proved, successful confirmed attack on Tiaoxin as of today.

Thank you for the `hpenc` and sorry for the noise
